### ISSUE TITLE
mpvue中，报对象对象循环引用错误

### ISSUE THREAD

**Issue by YuYanDev** [rchunping/wxapp-google-analytics#13]
``` js
jsEnginScriptError
Converting circular structure to JSON
    --> starting at object with constructor 'GoogleAnalytics'
    |     property 'app' -> object with constructor 'Object'
    --- property 'defaultGoogleAnalyticsInstance' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'GoogleAnalytics'
    |     property 'app' -> object with constructor 'Object'
    --- property 'defaultGoogleAnalyticsInstance' closes the circle
    at JSON.stringify (<anonymous>)
    at e.exports.send (http://127.0.0.1:22873/appservice/appservice?t=1566791304645:3716:1934)
    at Object.send (http://127.0.0.1:22873/appservice/appservice?t=1566791304645:3716:36326)
    at Object.n [as publish] (http://127.0.0.1:22873/appservice/appservice?t=1566791304645:3716:26795)
    at Object.publish (http://127.0.0.1:22873/appservice/__dev__/WAService.js:4:26509)
    at V (http://127.0.0.1:22873/appservice/__dev__/WAService.js:6:8453)
    at Object.Dd [as invokeWebviewMethod] (http://127.0.0.1:22873/appservice/__dev__/WAService.js:12:28515)
    at Function.value (http://127.0.0.1:22873/appservice/__dev__/WAService.js:19:11187)
    at t.value (http://127.0.0.1:22873/appservice/__dev__/WAService.js:19:15304)
    at http://127.0.0.1:22873/appservice/common/vendor.js:5544:3
```

按照 [issue 12](https://github.com/rchunping/wxapp-google-analytics/issues/12)中方式调用

ga统计正常发送，但是报错已经影响页面正常渲染

**Comment by rchunping** [comment]
这个库没用到JSON.stringify

你是不是把什么东西挂到data上去了？

**Comment by YuYanDev** [comment]
> 这个库没用到JSON.stringify
> 
> 你是不是把什么东西挂到data上去了？

GoogleAnalytics.getInstance挂data上去了，mixin混入的，在onload混入GA实例，onshow触发pv打点

**Comment by rchunping** [comment]
不要把实例挂data上，你用的地方import就可以了。

**Comment by YuYanDev** [comment]
> 不要把实例挂data上，你用的地方import就可以了。

可以了，不过这样代码重复率太高，强迫症有点点痛苦哈哈哈哈哈

**Comment by rchunping** [comment]
你可以挂vue实例上，只要不是data上就行。
